version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install phase started"

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - ls -l target

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - target/hello-world-web-app.war
